### ISSUE TITLE
"failed to grab name change info" when trying to prename snipe

### ISSUE THREAD

**Issue by LoganDark** [Kqzz/MCsniperGO#11]
# Bug Report
## Description
Snipe failed, presumably because the program doesn't support prename and that's not specified anywhere.

## Steps to reproduce
Try to snipe using an account that hasn't claimed its first username yet

## Expected result
Either snipe succeeded or someone actually claims the name before me

## Actual result
```
[info] » Sniping g51 at 2021/10/18 08:42:31

[info] » authenticating <censored> through ms auth
[success] » successfully authenticated <censored>
[err] » failed to verify that <censored> can snipe: failed to grab name change info
[err] » <censored> not ready to snipe
[fatal err] » no accounts successfully authenticated!
```

## Complete output
(already above)

---

PS, do you know how annoying this issue form is? I have to spread the information out across many sections when it would be much more natural to explain it in a single paragraph with output below.

**Comment by LoganDark** [comment]
> ok, so the issue is you used the ms “flag” and not “prename”

I have no idea what that means, I didn't put "flag" anywhere

**Comment by Kqzz** [comment]
> > i’ll write a more descriptive error message
> 
> By the time that error shows up, it's already too late, so please do some validation of the account on startup

riiiight… i changed that recently, it used to be8 hrs before. i might change that later.

**Comment by Kqzz** [comment]
ok, so, for doing the checks at the start:
It authenticates at the end because if you start a sniper and then, before the snipe is run, start another sniper, the first sniper started will return 401s because the first bearer token becomes invalid by the second token being created. 

It _is_ possible to check if an account hasn't been named, and that's exactly what happens if the account is marked as prename in `accounts.txt`. I see where you're coming from for automatically inferring if it's prename or not, so maybe I'll make an issue for that and implement it at some point. If I implement that, I'd feel like checking if it's Microsoft or Mojang and authing based off of that could be a good idea... But that's a bit more complicated and will include even more requests which _could_ potentially cause ratelimiting problems.

**Comment by Kqzz** [comment]
> > also, it shouldn't be 20 seconds before the snipe, the default is 15 minutes.
> 
> oh my bad, it said sniping in 20s so I assumed the login messages right before it also happened 20 seconds before
> 
> > It authenticates at the end because if you start a sniper and then, before the snipe is run, start another sniper, the first sniper started will return 401s because the first bearer token becomes invalid by the second token being created.
> 
> you can just verify at the start and use it for detecting things about the account - whether the password is valid, whether it's mojang or m$, whether it's prename or not, etc. then you can tell the user if their snipe is going to fail before the snipe actually happens, so they can work on fixing up the issues and then trying again.
> 
> you could either re-use the tokens or just generate new ones a short period before like you do now

good idea, I'll think about doing all of that.
