### ISSUE TITLE
Failed to authenticate my account

### ISSUE THREAD

**Issue by Ihavenoiqq** [Kqzz/MCsniperGO#28]
I typed in the code to link my account and it seemed to work but then it started to crash and say it failed to authenticate my account, I don’t know why this happens but help would be nice.

**Comment by Ihavenoiqq** [comment]
I am also on a Microsoft account, I don’t know if that changes anything but yeah.

**Comment by overestimate** [comment]
did you compile from source? if not, you need to do so and then set the account's password field to `oauth2-external` due to the parser being bugged at the moment
also, build v2.6's oauth login is messed up due to it concurrently running the auth, so you *have* to build from source or use another auth method

**Comment by overestimate** [comment]
@Kqzz if you could recompile using latest commit to `main` it'll work from releases
